name: Python package tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-name:
          - centos/python-27-centos7
          - centos/python-38-centos7
    container:
      image: ${{ matrix.container-name }}
      options: --user root

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        rpm -ivh ${{ secrets.REDACTED_URL }}centos/7.5.1804/exabyte/x86_64/Packages/torque-6.0.0.1-1.adaptive.el7.centos.x86_64.rpm
        rpm -ivh ${{ secrets.REDACTED_URL }}centos/7.5.1804/exabyte/x86_64/Packages/torque-devel-6.0.0.1-1.adaptive.el7.centos.x86_64.rpm
        bash -c 'python -m pip install --upgrade pip'
        bash -c 'python -m pip install --upgrade setuptools wheel'
        bash -c 'pip install -r requirements-dev.txt --no-deps'

    - name: Unit tests
      run: |
        bash -c 'python -m unittest discover --verbose --catch --start-directory tests/unit'
