name: Python package tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:7.5.1804
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        rpm -ivh ${{ secrets.REDACTED_URL }}centos/7.5.1804/exabyte/x86_64/Packages/torque-6.0.0.1-1.adaptive.el7.centos.x86_64.rpm
        rpm -ivh ${{ secrets.REDACTED_URL }}centos/7.5.1804/exabyte/x86_64/Packages/torque-devel-6.0.0.1-1.adaptive.el7.centos.x86_64.rpm
        pip install -r requirements-dev.txt --no-deps

    - name: Unit tests
      run: |
        python -m unittest discover --verbose --catch --start-directory tests/unit
